# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: MIS Service Request
    url: https://github.com/mis-bghmc/.github/issues/new?template=mis-service-request.yml
    about: Official MIS Service Request Form

  - name: Systems Development Request
    url: https://github.com/mis-bghmc/.github/issues/new?template=systems-development-request.yml
    about: New system, enhancement, or bug fix requests

